#ifndef CONFIG_H
#define CONFIG_H


#define MAYNARD_PANEL_WIDTH 56
#define MAYNARD_PANEL_HEIGHT_RATIO 0.73
#define MAYNARD_CLOCK_WIDTH (MAYNARD_PANEL_WIDTH * 2.6)
#define MAYNARD_CLOCK_HEIGHT (MAYNARD_PANEL_WIDTH * 2)
#define GRID_ITEM_WIDTH 114
#define GRID_ITEM_HEIGHT 114
#define MAYNARD_VERTICAL_CLOCK_WIDTH 25



#endif //CONFIG_H